Update host_monitor.yml
timeout 30 sec

diff --git a/.github/workflows/host_monitor.yml b/.github/workflows/host_monitor.yml
--- a/.github/workflows/host_monitor.yml
+++ b/.github/workflows/host_monitor.yml
@@ -12,7 +12,7 @@ jobs:
         id: check
         run: |
           # Пробуем получить ответ от HA с таймаутом 10 секунд
-          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 20 http://chapay.duckdns.org:8123/ || echo "CURL_ERROR")
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 http://chapay.duckdns.org:8123/ || echo "CURL_ERROR")
           
           # Home Assistant может возвращать 401 (Unauthorized) при работающем сервисе
           if [[ "$RESPONSE" =~ ^(200|401)$ ]]; then
